/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectwarehouse.Frame;

import java.sql.ResultSet;
import java.text.ParseException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import projectwarehouse.Controller.MainController;
import projectwarehouse.Helper.Helper;
import projectwarehouse.Model.MainModel;
import projectwarehouse.Model.UserModel;

/**
 *
 * @author Office
 */
public class MainFrame extends javax.swing.JFrame {

    
    MainModel model = new MainModel();
    MainController controller = new MainController();
    DefaultTableModel defaultModel;
    
    Helper helper = new Helper();
    String product_id;
    ResultSet rs;
    
    public MainFrame(UserModel userModel) {
        initComponents();
        this.clear();
        
        String labelMessage = "Hi, " + userModel.getName() + " insert your product name";
        this.label_name.setText(labelMessage);
    }
    
    public MainFrame() {
//        initComponents();
//        this.clear();
          return;
    }
    
    public void clear() {
        tf_name.setText("");
        tf_stock.setText("");
        cb_type.setSelectedIndex(0);
        dp_inputDate.setDate(null);
        
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_out.setEnabled(false);
    }
    public void getAllData() {
        this.rs = controller.get();
        this.loadTableIn(this.rs);
    }
    public void getAllDataOut() {
        this.rs = controller.get();
        this.loadTableOut(this.rs);
    }
    
//    private void updatebarangmasuk(){
//        try{
//        int stock = Integer.parseInt(tf_stock.getText());
//        String ids = tf_pid.getText();
//        this.product_id = ids;
//        model.setStock(Stock);
//        
//        controller.stockdecreasebarangmasuk(this.product_id, model);
//        }catch(Exception e){
//            System.out.println(e.getMessage());
//        }
//    }
//    private void insertbarangkeluar(){
//        try{
////        int stock = Integer.parseInt(tf_stock.getText());
////        String ids = tf_pid.getText();
////        this.product_id = ids;
////        model.setStock(ids);
//        controller.stockinsertbarangkeluar(this.product_id, model);
//        }catch(Exception e){
//            System.out.println(e.getMessage());
//        }
//    }
    
//    private void method(){
//        try{
//        controller.stockinsertbarangkeluar(this.product_id, model);
//        controller.stockdecreasebarangmasuk(this.product_id, model);
//        }catch(Exception e){
//            System.out.println(e.getMessage());
//        }
//    }
    
    private void showTableIn(){
        this.rs = controller.get();
        this.loadTableIn(this.rs);
    }
    
    private void showTableOut(){
        this.rs = controller.get();
        this.loadTableOut(this.rs);
    }
    
    public void loadTableIn(ResultSet rs) {
        tb_product_in.setModel(DbUtils.resultSetToTableModel(rs));
    }
    public void loadTableOut(ResultSet rs) {
        tb_product_out.setModel(DbUtils.resultSetToTableModel(rs));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label_name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dp_inputDate = new org.jdesktop.swingx.JXDatePicker();
        tf_name = new javax.swing.JTextField();
        cb_type = new javax.swing.JComboBox<>();
        tf_stock = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_product_in = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        tf_search = new javax.swing.JTextField();
        btn_searchName = new javax.swing.JButton();
        btn_searchID = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_out = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_product_out = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Project Warehouse Inventory");

        label_name.setText("Nama Barang");

        jLabel3.setText("Jenis Barang");

        jLabel4.setText("Jumlah Barang");

        jLabel5.setText("Tanggal");

        dp_inputDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dp_inputDateActionPerformed(evt);
            }
        });

        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameActionPerformed(evt);
            }
        });

        cb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shirt", "Pants", "Shoes" }));
        cb_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_typeActionPerformed(evt);
            }
        });

        tf_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_stockActionPerformed(evt);
            }
        });

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        tb_product_in.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tb_product_in.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_product_in.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_product_inMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_product_in);

        jLabel6.setText("Pencarian");

        btn_searchName.setText("Cari dengan nama");
        btn_searchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchNameActionPerformed(evt);
            }
        });

        btn_searchID.setText("Cari dengan ID");
        btn_searchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Tabel Barang Masuk");

        btn_out.setText("Out");
        btn_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_outActionPerformed(evt);
            }
        });

        tb_product_out.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_product_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_product_outMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_product_out);

        jLabel7.setText("Tabel Barang Keluar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_name)
                                .addComponent(cb_type, 0, 142, Short.MAX_VALUE)
                                .addComponent(tf_stock)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_update)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_delete))
                                .addComponent(dp_inputDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(4, 4, 4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf_search, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btn_searchName)
                        .addGap(18, 18, 18)
                        .addComponent(btn_searchID))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(btn_out, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_name)
                            .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_searchName)
                            .addComponent(btn_searchID))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(btn_submit)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dp_inputDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_update)
                            .addComponent(btn_delete))
                        .addGap(61, 61, 61))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btn_out))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nameActionPerformed

    private void tf_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_stockActionPerformed

    private void cb_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_typeActionPerformed

    private void dp_inputDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dp_inputDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dp_inputDateActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        try {
            String name = tf_name.getText();
            String stock = tf_stock.getText();
            String type = cb_type.getSelectedItem().toString();

            Date date = dp_inputDate.getDate();

            model.setName(name);
            model.setType(type);
            model.setInputdate(date);
            model.setStock(stock);

            Boolean result = controller.create(model);
            
            String msg = "Gagal menambahkan data!";
            if(result) {
                msg = "Berhasil menambahkan data";
            }
            
            JOptionPane.showMessageDialog(null, msg);
            this.clear();
            this.getAllData();
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void tb_product_inMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_product_inMouseClicked
        try {
            // TODO add your handling code here:
            String id = helper.getValueRows(tb_product_in, 0);
            String name = helper.getValueRows(tb_product_in, 1);
            String type = helper.getValueRows(tb_product_in, 2);
            String stock = helper.getValueRows(tb_product_in, 3);
            String inputdate = helper.getValueRows(tb_product_in, 4);
            
            btn_update.setEnabled(true);
            btn_delete.setEnabled(true);
            btn_out.setEnabled(true);
            
            Date date = new Date(helper.parseStringToDatePickerFormat(inputdate));
            
            this.product_id = id;
            tf_name.setText(name);
            cb_type.setSelectedItem(type);
            tf_stock.setText(stock);
            dp_inputDate.setDate(date);
        } catch (ParseException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_tb_product_inMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.getAllData();
    }//GEN-LAST:event_formWindowOpened

    private void btn_searchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchNameActionPerformed
        this.search("name", tf_search.getText());
    }//GEN-LAST:event_btn_searchNameActionPerformed

    private void btn_searchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchIDActionPerformed
        this.search("id", tf_search.getText());
    }//GEN-LAST:event_btn_searchIDActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
            String name = tf_name.getText();
            String stock = tf_stock.getText();
            String type = cb_type.getSelectedItem().toString();

            Date date = dp_inputDate.getDate();

            model.setName(name);
            model.setType(type);
            model.setInputdate(date);
            model.setStock(stock);

            Boolean result = controller.update(this.product_id, model);
            
            String msg = "Gagal merubah data!";
            if(result) {
                msg = "Berhasil merubah data";
            }
            
            JOptionPane.showMessageDialog(null, msg);
            this.clear();
            this.getAllData();
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try {
            
            Boolean result = controller.delete(this.product_id);
            
            String msg = "Gagal menghapus data!";
            if(result) {
                msg = "Berhasil menghapus data";
            }
            
            JOptionPane.showMessageDialog(null, msg);
            
            this.clear();
            this.getAllData();
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void tb_product_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_product_outMouseClicked
         
    }//GEN-LAST:event_tb_product_outMouseClicked

    private void btn_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_outActionPerformed
        try {
            String name = tf_name.getText();
            String stock = tf_stock.getText();
            String type = cb_type.getSelectedItem().toString();

            Date date = dp_inputDate.getDate();
                    
            model.setName(name);
            model.setType(type);
            model.setInputdate(date);
            model.setStock(stock);

            Boolean result1 = controller.stockdecreasebarangmasuk(this.product_id, model);
            Boolean result2 = controller.stockinsertbarangkeluar(this.product_id, model);
            
            String msg = "Gagal merubah data!";
            
            if(result1&&result2) {
                msg="Berhasil merubah data";
            }
            
            JOptionPane.showMessageDialog(null, msg);
            showTableIn();
            showTableOut();
//            method();
//            updatebarangmasuk();
//            insertbarangkeluar();
            this.clear();
            this.getAllDataOut();
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_outActionPerformed
    
    private void search(String type, String query) {
        try {
            if(query.isEmpty()) {
                this.rs = controller.get();
            } else if (type.equals("id") && !query.isEmpty()) {
                this.rs = controller.showById(query);
            } else if (type.equals("name") && !query.isEmpty()) {
                this.rs = controller.showByName(query);
            }
            
            this.loadTableIn(this.rs);
        }catch(Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_out;
    private javax.swing.JButton btn_searchID;
    private javax.swing.JButton btn_searchName;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cb_type;
    private org.jdesktop.swingx.JXDatePicker dp_inputDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_name;
    private javax.swing.JTable tb_product_in;
    private javax.swing.JTable tb_product_out;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_search;
    private javax.swing.JTextField tf_stock;
    // End of variables declaration//GEN-END:variables
}
